### ISSUE TITLE
request blocking does not work correctly

### ISSUE THREAD

**Issue by IvanIin** [AdguardTeam/DnsLibs#49] opened 2020-02-03 12:52 UTC
whitelist rules must have higher priority in any case

how to reproduce:
- add blocking rule "||datamind.ru^"
- add whitelist rule "@@||sync.datamind.ru^|"
- request "sync.datamind.ru"

expected result:
receive an answer with IP address

actual result:
receive an answer with NXDOMAIN

**Comment by sfionov** [comment] 2020-02-03 12:58
Not in any, but priority order is:
whitelist,important rule
important rule
whitelist rule
regular rule

**Comment by ngorskikh** [comment] 2020-02-03 13:08
The problem is not with priority, this hostname is blocked by CNAME blocking: 
```
[2020-02-03 16:07:23.741905] [1264510] [DNS forwarder] [trace] [44713] apply_cname_filter Response CNAME: prod-hzeu-rtb-anthill-app.datamind.ru
[2020-02-03 16:07:23.742033] [1264510] [dnsfilter] [trace] Matching prod-hzeu-rtb-anthill-app.datamind.ru
[2020-02-03 16:07:23.742322] [1264510] [1::user.txt] [debug] Domain 'prod-hzeu-rtb-anthill-app.datamind.ru' matched against rule '||datamind.ru^'
[2020-02-03 16:07:23.742363] [1264510] [dnsfilter] [trace] Matched 1 rules
[2020-02-03 16:07:23.742381] [1264510] [DNS forwarder] [trace] [44713] apply_filter Matched rule: ||datamind.ru^
[2020-02-03 16:07:23.742403] [1264510] [DNS forwarder] [debug] [44713] apply_filter DNS query blocked by rule: ||datamind.ru^
```
Need to decide what to do in this kind of case :)

**Comment by ameshkov** [comment] 2020-02-03 13:09
There's nothing to decide, the behavior we need is described in the issue text.

**Comment by ngorskikh** [comment] 2020-02-03 13:10
@ameshkov should we disable CNAME matching if the original request was whitelisted?

**Comment by ameshkov** [comment] 2020-02-03 13:11
Sure

**Comment by ngorskikh** [comment] 2020-02-03 13:12
@ameshkov same for IP, just to be sure?

**Comment by sfionov** [comment] 2020-02-03 13:21
It is strange that this was not fixed by #41

**Comment by ngorskikh** [comment] 2020-02-03 13:22
@sfionov here, the white-list rule does NOT match the CNAME, hence my initial hesitation

**Comment by ameshkov** [comment] 2020-02-03 13:23
This is exactly the same situation in #41

**Comment by sxgunchenko** [comment] 2020-02-03 13:29
guys, #41's name does not relate to the cause of the issue
there we have discarded the rule which should've matched against cname

**Comment by ngorskikh** [comment] 2020-02-03 13:30
Well, in #41 the request is blocked before we can even _know_ the CNAME (we don't query the upstreams for blocked requests). Seems like #41 was not actually fixed. It should have also prompted the discussion about whitelisting by CNAME :)

**Comment by ngorskikh** [comment] 2020-02-03 14:15
dns-libs/pull-requests/83

**Closed** 2020-02-10 09:24 UTC
Labels: bug
