### ISSUE TITLE
Look like Adguard Android doesnt support HTTP3

### ISSUE THREAD

**Issue by nkoc6a15** [AdguardTeam/DnsLibs#121] opened 2021-09-19 02:45 UTC
I have try disable Adguard DNS section in Adguard and use DoT in Android and see HTTP3 is back (Test with https://cloudflare-quic.com/) but when i enable Adguard DNS section again, HTTP3 gone. Can you guy support http3? Maybe in v4?

**Comment by Chinaski1** [comment] 2021-09-20 08:49
Hello there!

Does it stop being supported even if you select a system server in the AdGuard DNS settings?

Also, we have our own DNS-over-QUIC which uses the HTTP3 protocol.

**Comment by sfionov** [comment] 2021-09-20 10:00
I think this task is about QUIC blocking performed by AdGuard since it can't filter it.

We are planning to add QUIC and HTTP/3 support in several steps.

In one of next releases "QUIC bypass" filtering will be introduced - so we will filter QUIC in apps without HTTPS filtering.

After that, when fully-functional HTTP/3 filtering will be available, we will stop blocking it in browsers too.

I'm closing this issue as duplicate of https://github.com/AdguardTeam/CoreLibs/issues/487

**Closed by sfionov** 2021-09-20 10:00 UTC
