### ISSUE TITLE
Examine the native apps ad blocking on iOS

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/DnsLibs#110] opened 2021-05-30 20:45 UTC
Check out this comment: https://github.com/AdguardTeam/AdguardForiOS/issues/1755#issuecomment-851053960

It seems that for some reason the quality of blocking is worse in Split Tunnel mode, and I've no idea why.

Let's compare the app's DNS requests in both modes, maybe we'll see the difference.

**Comment by ameshkov** [comment] 2021-06-01 06:55
Relevant report to Apple dev forums: https://developer.apple.com/forums/thread/679702

We should file a bug report to Apple as well.

**Comment by ngorskikh** [comment] 2021-06-04 09:19
I've filed a bug report (FB9126588). The issue reproduces when the NEDNSSettings API is used "as intended".

**Comment by ngorskikh** [comment] 2021-06-08 13:56
On iOS 15 beta DNS leaking seems to be fixed (at least for now).
However, now when `iCloud Private Relay` is enabled, DNS traffic never goes through our tunnel in split tunnel mode.

**Comment by ngorskikh** [comment] 2021-06-11 15:50
The original issue seems to be fixed in both iOS 15 and 14.7
Now we just need to wait for them to be released 🙃

**Closed** 2021-12-20 12:39 UTC
Labels: question, Resolution: Fixed, Status: Resolved, Version: DnsLibs v1.6, iOS Bug
