### ISSUE TITLE
"ttp" rule would block access to many domains

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/DnsLibs#118] opened 2021-08-06 12:30 UTC
https://github.com/AdguardTeam/AdGuardDNS/issues/182

**Comment by sfionov** [comment] 2021-08-06 13:08
Basically we apply "exact match" for string without | and ^, but they are also checked if they are domains.

We may allow domains without dots in such cases.

**Comment by ameshkov** [comment] 2021-08-06 13:40
I mean `ttp` would match `example.org` that does not have the `ttp` substring in it.

**Comment by ngorskikh** [comment] 2021-09-29 15:08
Couldn't reproduce with `example.org`. However, `ttp` is interpreted as a pattern, not an exact domain name, and anything with `ttp` in it (including in CNAME) matches. Fixed in dns-libs/pull-requests/319

**Closed** 2021-10-06 10:17 UTC
Labels: bug, Resolution: Fixed, Status: Resolved
