### ISSUE TITLE
basicincome.gg.go.kr

### ISSUE THREAD

**Issue by piquark6046** [AdguardTeam/DnsLibs#123] opened 2021-10-02 02:59 UTC
https://github.com/AdguardTeam/AdguardFilters/issues/96237

Not only AdGuard for iOS but also AdGuard for Android(3.6.4) breaks this website.
However, On AdGuard Browser Extension and Windows(7.7 n23), the website is not broken.

**Comment by sfionov** [comment] 2021-10-04 09:53
Duplicate of #124 (moved from another repo).

You may temporary add DNS rule like 

```
175.106.80.64 basicincome.gg.go.kr
```
(IP taken from dig output)

**Closed** 2021-10-05 08:52 UTC
Labels: Version: DnsLibs v1.6
